require: rubocop-performance

inherit_gem:
  onkcop:
    - "config/rubocop.yml"
    # uncomment if use rails cops
    # - "config/rails.yml"
    - "config/rspec.yml"

AllCops:
  TargetRubyVersion: 3.2
  # uncomment if use rails cops
  # TargetRailsVersion: 5.0
  NewCops: enable
  SuggestExtensions: false

Layout/HashAlignment:
  EnforcedColonStyle:      table
  EnforcedHashRocketStyle: table

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Lint/ScriptPermission:
  Enabled: false

Metrics/BlockLength:
  Max: 28

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/SpecFilePathFormat:
  Exclude:
    - spec/lib/syobocalite_ext_spec.rb

Style/FetchEnvVar:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
