inherit_gem:
  onkcop:
    - "config/rubocop.yml"
    # uncomment if use rails cops
    # - "config/rails.yml"
    - "config/rspec.yml"

AllCops:
  TargetRubyVersion: 2.5
  # uncomment if use rails cops
  # TargetRailsVersion: 5.0

Lint/ScriptPermission:
  Enabled: false

Metrics/BlockLength:
  Max: 28

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
