require: rubocop-performance

inherit_gem:
  onkcop:
    - "config/rubocop.yml"
    # uncomment if use rails cops
    # - "config/rails.yml"
    - "config/rspec.yml"

AllCops:
  TargetRubyVersion: 2.6
  # uncomment if use rails cops
  # TargetRailsVersion: 5.0
  NewCops: enable

Layout/HashAlignment:
  EnforcedColonStyle:      table
  EnforcedHashRocketStyle: table

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Lint/ScriptPermission:
  Enabled: false

Metrics/BlockLength:
  Max: 28

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
