default:
  servers:
    - "localhost:11211"
  options:
    namespace: "cure-mastodon-bots"
    compress: true
    expires_in: <%= 1.second %>

production:
  servers: <%= ENV["MEMCACHEDCLOUD_SERVERS"]&.split(",") %>
  options:
    expires_in: <%= 1.hour %>
    username: <%= ENV["MEMCACHEDCLOUD_USERNAME"] %>
    password: <%= ENV["MEMCACHEDCLOUD_PASSWORD"] %>
